Issues #118, #119. Add suite2p/facemap roadmaps
datajoint/datajoint-elements pull request #120
Opened 2022-06-15 16:08 UTC by CBroz1

2022-06-15 16:09 UTC, CBroz1 commented
@kabilar - Please review the links I added for the Facemap Development Roadmap. These were missing from the google doc.

2022-06-17 22:33 UTC, kabilar requested changes
Thanks @CBroz1!

2022-06-17 22:33 UTC, kabilar commented on docs/community/suite2p.md
> +- Tutorials on running DataJoint Element with Suite2p - Completed 2022 -
```suggestion
- Tutorials on running DataJoint Element with Suite2p - Completed 2021 -
```

2022-06-17 22:33 UTC, kabilar commented on docs/community/facemap.md
> +[Link](https://github.com/datajoint/element-facemap/blob/main/element_facemap/facial_behavior_estimation.py#L389-L405)
```suggestion
[Element Facemap](https://github.com/datajoint/element-facemap/blob/0ccab4ec6731cd612e7cf61a221c64fb9bf22566/element_facemap/facial_behavior_estimation.py#L389-L405)
```

2022-06-17 22:33 UTC, kabilar commented on docs/community/facemap.md
> +[Link](https://github.com/datajoint/element-facemap/blob/main/element_facemap/facial_behavior_estimation.py#L259-L266)
```suggestion
[Element Facemap](https://github.com/datajoint/element-facemap/blob/0ccab4ec6731cd612e7cf61a221c64fb9bf22566/element_facemap/facial_behavior_estimation.py#L259-L266)
```

2022-06-17 22:33 UTC, kabilar commented on docs/community/facemap.md
> +### Neurodata without Borders (Facemap)
```suggestion
### Facemap
```

2022-06-17 22:33 UTC, kabilar commented on docs/community/facemap.md
> +calcium imaging data. The project is funded by HHMI Janelia Research Campus and led by
```suggestion
imaging data. The project is funded by HHMI Janelia Research Campus and led by
```

2022-06-17 22:33 UTC, kabilar commented on docs/community/facemap.md
> +The principal developers of Facemap are at Janelia Research Campus.
```suggestion
The principal developers of Facemap are at the Janelia Research Campus.
```

2022-06-17 22:33 UTC, kabilar commented on docs/community/suite2p.md
> +The principal developers of Suite2p are at Janelia Research Campus.
```suggestion
The principal developers of Suite2p are at the Janelia Research Campus.
```

2022-06-17 22:33 UTC, kabilar commented on docs/community/facemap.md
> +workflows and Facemap utilities.
```suggestion
that avoid any hindrance to integration and interoperability between DataJoint Elements 
and Facemap.
```

2022-06-17 22:33 UTC, kabilar commented on docs/community/facemap.md
> +If you use this package please cite
```suggestion
If you use Facemap please cite 
```

2022-06-20 15:18 UTC, CBroz1 commented
@kabilar Thanks for your review. Ready to merge when you're back from PTO

2022-06-27 16:26 UTC, kabilar approved these changes
Thanks @CBroz1!

2022-06-27 16:26 UTC, merged